### PR TITLE
Fix Support us Page

### PR DESCRIPTION
**Pull request by daniel-panhead**
I forgot about this page before I merged the other PR lol

Also please populate Budget of each Phase @IcedTea2K 

image

### CODE REVIEW

**Comment by IcedTea2K** [comment]
image
image

**Comment by IcedTea2K** [comment]
@daniel-panhead  Was looking through the navbar again. currentPath is only set once, and it's never set again. So when you click onto different page, the old page is still highlighted dark blue (primary color).
```
function Navbar() {
  const [currentPath, setCurrentPath] = useState("/");

  useEffect(() => {
    setCurrentPath(window.location.pathname);
  }, []);
```

EDIT: Fixed by adding an onclick listener

**Review by IcedTea2K — APPROVED** [review]
👍

**Comment by daniel-panhead** [comment]
oh that's why it doesnt work lol

**Pull request merged**
